networks:
  traefik:
    name: traefik
    external: true

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    networks:
      - traefik
    expose:
      - 9000
    volumes:
      - ./data:/data
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.routers.portainer.tls: "true"
        traefik.http.routers.portainer.tls.certresolver: production
        traefik.http.routers.portainer.service: portainer
        traefik.http.routers.portainer.rule: Host(`portainer.c.ds.kobu.au`)
        traefik.http.services.portainer.loadbalancer.server.port: 9000
