networks:
  traefik:
    name: traefik
    external: true

volumes:
  nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.i.kobu.au,rw
      device: ":/volume1/ds/portainer"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    networks:
      - traefik
    expose:
      - 9000
    volumes:
      - type: volume
        source: nfs
        target: /app
        volume:
          nocopy: true
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.routers.portainer.tls: "true"
        traefik.http.routers.portainer.tls.certresolver: production
        traefik.http.routers.portainer.service: portainer
        traefik.http.routers.portainer.rule: Host(`portainer.c.ds.kobu.au`)
        traefik.http.services.portainer.loadbalancer.server.port: 9000
